src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Effective_Action_Date__c</fullName>
        <formula>IF (  Campaign.StartDate &lt;=  FirstRespondedDate &amp;&amp; Campaign.EndDate &gt;= FirstRespondedDate &amp;&amp; NOT(ISBLANK(Campaign.StartDate)) &amp;&amp; NOT(ISBLANK(Campaign.EndDate)) &amp;&amp; NOT(ISBLANK(FirstRespondedDate)) , FirstRespondedDate , Campaign.StartDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>if the FirstRespondedDate (the date contact was marked Responded for the campaign) is between campaign start &amp; end dates (meaning it has both), it&apos;ll use the responded date (important for long campaigns).  Otherwise, it&apos;ll just use campaign start date.</inlineHelpText>
        <label>Effective Action Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Engagement_Conversion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Engagement Conversion</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/GW_CTRL_DashMetrics.cls
public with sharing class GW_CTRL_DashMetrics {

	public integer ttlConversions {get;set;}
	public integer oppConversions {get;set;}
	public integer campConversions {get;set;}
	date ninetyDayCutoff;
	
	public GW_CTRL_DashMetrics() {
		this.ninetyDayCutoff = system.today().addDays(-90);
		calcConvTotals();
	}

	private void calcConvTotals() {
		// tbd add namespace prefixes
		string soql = 'SELECT Count() FROM Opportunity WHERE CloseDate >= :ninetyDayCutoff AND Engagement_Conversion__c = true ';
		oppConversions = database.countQuery(soql);
		if (oppConversions==null) oppConversions = 0; 

		string soql2 = 'SELECT Count() FROM CampaignMember WHERE Effective_Action_Date__c >= :ninetyDayCutoff AND Engagement_Conversion__c = true ';
		campConversions = database.countQuery(soql2);
		if (campConversions==null) campConversions = 0; 
		
		ttlConversions = oppConversions + campConversions;

	}

}