src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Leadership_Level__c</fullName>
        <inlineHelpText>Level of leadership: 1-organizing, 2-consistent leader, 3-inconsistent leader, 4-activist, 5-donor/member</inlineHelpText>
        <label>Campaign Engagement Level</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Observing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Following</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Endorsing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Contributing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 - Owning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 - Leading</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Engagement_Level_Override__c</fullName>
        <inlineHelpText>This will increase the contact&apos;s engagement level, if this level is higher than what they would otherwise get based on their activity/donor history.  It cannot lower their level, only raise it.  It is effective until the override end date specified.</inlineHelpText>
        <label>Engagement Level Override</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Following</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Endorsing</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Contributing</fullName>
                <color>#FF9900</color>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Owning</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>5 - Leading</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Engagement_Level__c</fullName>
        <description>set by batch process</description>
        <inlineHelpText>Current engagement level, automatically calculated.  If you want to manually change the level, do not attempt to change this field.  Instead, enter a value in Engagement Level Override.</inlineHelpText>
        <label>Engagement Level</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Following</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Endorsing</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Contributing</fullName>
                <color>#FF9900</color>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Owning</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>5 - Leading</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Engagement_Peak__c</fullName>
        <inlineHelpText>The highest engagement level ever reached by this contact.

NOTE: This does not take into account any past overrides or formerly-checked checkboxes that affect engagement level.</inlineHelpText>
        <label>Engagement Peak</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Following</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Endorsing</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Contributing</fullName>
                <color>#FF9900</color>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Owning</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>5 - Leading</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/EngagementTrackerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Level_1_Name__c</fullName>
        <defaultValue>&quot;1 - Following&quot;</defaultValue>
        <label>Level 1 Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_2_Name__c</fullName>
        <defaultValue>&quot;2 - Endorsing&quot;</defaultValue>
        <label>Level 2 Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_3_Name__c</fullName>
        <defaultValue>&quot;3 - Contributing&quot;</defaultValue>
        <label>Level 3 Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_4_Name__c</fullName>
        <defaultValue>&quot;4 - Owning&quot;</defaultValue>
        <label>Level 4 Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_5_Name__c</fullName>
        <defaultValue>&quot;5 - Leading&quot;</defaultValue>
        <label>Level 5 Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_6_Name__c</fullName>
        <label>Level 6 Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_7_Name__c</fullName>
        <label>Level 7 Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_8_Name__c</fullName>
        <label>Level 8 Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Groundwire Engage General Settings</label>
</CustomObject>

src/classes/GW_CTRL_ETSettingsTabLevels.cls
public with sharing class GW_CTRL_ETSettingsTabLevels {
	
	// constructor
	public GW_CTRL_ETSettingsTabLevels(GW_CTRL_ETSettingsWizard cWiz) {
		ctrlWizard = cWiz;
		isEditingTab = false;
				
		// lookup values for engagement level picklist fields
		ReloadPicklistValues();		
	}

	private GW_CTRL_ETSettingsWizard ctrlWizard { get; set; }
	
	
	public EngagementTrackerSettings__c etSettings {
		get {
			if (etSettings == null) etSettings = GW_BATCH_EngagementRollup.settings;
			return etSettings;
		}
		set;
	}
	
	public boolean isEditingTab { get; set; }

	// strings for the four engagement level picklist fields
	private string strCELpicklist { get; set; }
	private string strCELOpicklist { get; set; }
	private string strCEPpicklist { get; set; }
	private string strCaELpicklist { get; set; }
	
	// strings lists for the four engagement level picklist fields
	public list<string> listStrCEL { get; set; }
	public list<string> listStrCELO { get; set; }
	public list<string> listStrCEP { get; set; }
	public list<string> listStrCaEL { get; set; }
	
	// using Describe, load up all the picklist values for the Engagement Level fields.
	private void ReloadPicklistValues() {
		
		strCELpicklist = '';	
		listStrCEL = new list<string>();
		for (Schema.PicklistEntry p : Contact.Engagement_Level__c.getDescribe().getPicklistValues()) {
			strCELpicklist += p.getLabel() + ';';			
			listStrCEL.add(p.getLabel());		
		}		

		strCELOpicklist = '';	
		listStrCELO = new list<string>();
		for (Schema.PicklistEntry p : Contact.Engagement_Level_Override__c.getDescribe().getPicklistValues()) {
			strCELOpicklist += p.getLabel() + ';';	
			listStrCELO.add(p.getLabel());		
		}		

		strCEPpicklist = '';	
		listStrCEP = new list<string>();
		for (Schema.PicklistEntry p : Contact.Engagement_Peak__c.getDescribe().getPicklistValues()) {
			strCEPpicklist += p.getLabel() + ';';			
			listStrCEP.add(p.getLabel());		
		}		

		strCaELpicklist = '';	
		listStrCaEL = new list<string>();
		for (Schema.PicklistEntry p : Campaign.Leadership_Level__c.getDescribe().getPicklistValues()) {
			strCaELpicklist += p.getLabel() + ';';			
			listStrCaEL.add(p.getLabel());		
		}		
	}
	

	public boolean isMatchingPicklists {
		get {
			string strLevels = 
				StrNullSemi(etSettings.Level_1_Name__c) +
				StrNullSemi(etSettings.Level_2_Name__c) +
				StrNullSemi(etSettings.Level_3_Name__c) +
				StrNullSemi(etSettings.Level_4_Name__c) +
				StrNullSemi(etSettings.Level_5_Name__c) +
				StrNullSemi(etSettings.Level_6_Name__c) +
				StrNullSemi(etSettings.Level_7_Name__c) +
				StrNullSemi(etSettings.Level_8_Name__c) ;
			return (strLevels == strCELpicklist &&
					strLevels == strCELOpicklist &&
					strLevels == strCEPpicklist &&
					strLevels == strCaELpicklist);
		}
	}
	
	private string StrNullSemi(string str) {
		if (str == null || str == '') return '';
		return str + ';';
	}
	
	public PageReference RetestPicklists() {
		ReloadPicklistValues();
		return null;	
	}
	
	public PageReference editTab() {
		isEditingTab = true;
		ctrlWizard.strCurrentTab = 'tabLevels';		
		return null;
	}
	
	public PageReference saveTab() {
		upsert etSettings;
		ctrlWizard.listSOLevels = null; // force them to reload
		isEditingTab = false;
		ctrlWizard.strCurrentTab = 'tabLevels';
		return null;
	}
	
	public PageReference cancelTab() {
		isEditingTab = false;
		etSettings = null;
		PageReference p = new PageReference('/apex/ETSettingsWizard?currentTab=tablevels');
		p.setRedirect(true);
		return p;
	}

}