src/objects/EngagementFrequencySettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Rules for what levels should be awarded for repeated similar actions</description>
    <fields>
        <fullName>Campaign_Record_Type__c</fullName>
        <inlineHelpText>(optional) If set, all campaigns must have this Record Type.</inlineHelpText>
        <label>Campaign Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Sub_Type__c</fullName>
        <inlineHelpText>(optional)  If set, all campaigns must have this sub-type.</inlineHelpText>
        <label>Campaign Sub Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Type__c</fullName>
        <inlineHelpText>(optional) If set, all campaigns must be of this Type.</inlineHelpText>
        <label>Campaign Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Value_1__c</fullName>
        <inlineHelpText>This field is no longer used.</inlineHelpText>
        <label>Field Value 1 - DEPRECATED</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fieldname_1__c</fullName>
        <inlineHelpText>This field is no longer used.</inlineHelpText>
        <label>Campaign Fieldname 1 - DEPRECATED</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_Required__c</fullName>
        <inlineHelpText>(optional) If set, all campaigns must be of this level.</inlineHelpText>
        <label>Level Required</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_To_Assign__c</fullName>
        <inlineHelpText>(required)  The Engagement Level they are eligible for if all conditions are met.</inlineHelpText>
        <label>Engagement Level</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Actions_Required__c</fullName>
        <inlineHelpText>(required)  The Contact must have this many Campaign Memberships within the usual timeframe to qualify.</inlineHelpText>
        <label>Number of Actions Required</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Groundwire Engage Frequency Settings</label>
</CustomObject>

src/classes/GW_CTRL_ETSettingsTabFrequency.cls
public with sharing class GW_CTRL_ETSettingsTabFrequency {

	// constructor
	public GW_CTRL_ETSettingsTabFrequency(GW_CTRL_ETSettingsWizard cWiz) {
		ctrlWizard = cWiz;
		isEditingTab = false;
	}
	
	private GW_CTRL_ETSettingsWizard ctrlWizard { get; set; }
	
    public List<EngagementFrequencySettings__c> listFreqSettings {
    	get {
    		if (listFreqSettings == null) {
    			listFreqSettings = EngagementFrequencySettings__c.getall().values();    			
    			AddEmptyRows();
    		}
    		return listFreqSettings;
    	}
    	set;
    }	

	public PageReference AddEmptyRows() {
		for (integer i = 0; i < 5; i++) {
			listFreqSettings.add(new EngagementFrequencySettings__c());
		}
		return null;
	}	

	public boolean isEditingTab { get; set; }
	
	public PageReference editTab() {
		isEditingTab = true;
		ctrlWizard.strCurrentTab = 'tabFrequency';
		return null;
	}
	
	public PageReference saveTab() {
		list<EngagementFrequencySettings__c> listFStoDel = new list<EngagementFrequencySettings__c>();
		  
		// go thru the frequency settings, and delete empty ones
		for (integer i = listFreqSettings.size()-1; i >= 0; i--) {
			EngagementFrequencySettings__c fs = listFreqSettings[i];
			if (isnullStr(fs.Fieldname_1__c) && 
				isnullStr(fs.Campaign_Record_Type__c) &&
				isnullStr(fs.Campaign_Sub_Type__c) &&
				isnullStr(fs.Campaign_Type__c) &&
				isnullStr(fs.Field_Value_1__c) &&
				isnullNum(fs.Level_Required__c) &&
				isnullNum(fs.Level_To_Assign__c) &&
				isnullNum(fs.Number_of_Actions_Required__c)) {
					if (fs.Id == null) {
						// it's a new empty dls; just remove it
						listFreqSettings.remove(i);
					} else {
						// it's an existing, but cleared entry; delete it.
						listFreqSettings.remove(i);
						listFStoDel.add(fs);
					}
			}
		}

		// name new settings
		ctrlWizard.nameNewSettings(listFreqSettings, 'FrequencySetting');

		if (listFStoDel.size() > 0) delete listFStoDel;
		upsert listFreqSettings;
		AddEmptyRows();
		isEditingTab = false;
		ctrlWizard.strCurrentTab = 'tabFrequency';
		return null;
	}
	
	public PageReference cancelTab() {
		isEditingTab = false;
		listFreqSettings = null;
		PageReference p = new PageReference('/apex/ETSettingsWizard?currentTab=tabFrequency');
		p.setRedirect(true);
		return p;
	}

	private boolean isnullStr(string str) {
		return (str == null || str == '');
	}

	private boolean isnullNum(decimal num) {
		return (num == null || num == 0);
	}

	//---------------------------------------- TEST CODE -------------------------------------------------
	static testmethod void TestTabFrequency() {
		GW_CTRL_ETSettingsWizard ctrl = new GW_CTRL_ETSettingsWizard();
		system.assert(ctrl.ctabFrequency != null);
		system.assertEquals(ctrl.ctabFrequency.ctrlWizard, ctrl);
		system.assertEquals(ctrl.ctabFrequency.isEditingTab, false);
		system.assert(ctrl.ctabFrequency.listFreqSettings != null);
		ctrl.ctabFrequency.editTab();
		system.assertEquals(ctrl.strCurrentEditTab, 'tabFrequency');
		ctrl.ctabFrequency.saveTab();
		system.assertEquals(ctrl.strCurrentEditTab, null);
		system.assert(ctrl.ctabFrequency.cancelTab() != null);		
	}
	
}