src/objects/Engagement_Totals__c.object
<CustomObject>
    <fields>
        <fullName>As_of_Date__c</fullName>
        <label>As of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Engagement_Level__c</fullName>
        <label>Engagement Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Contacts__c</fullName>
        <inlineHelpText>Number of Contacts</inlineHelpText>
        <label>Number of Contacts</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Engagement Totals</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Engagement Totals Nbr</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Totals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GW_CTRL_EngagementDashboard.cls
public with sharing class GW_CTRL_EngagementDashboard {


	// public list<sobject> aggResults {get;set;}
	public list<aggEngagementRow> rows {get;set;}
	public boolean noRecentData {get;set;}

	// constructor
	public GW_CTRL_EngagementDashboard () {
		this.rows = new list<aggEngagementRow>();
		queryEngagementCounts();
		
	}
	
	
	public void queryEngagementCounts () {
		
		// get the most recent day's totals from the analytic snapshot
		// first find out the most recent date we have data for - should be today unless early in the a.m. 
		Engagement_Totals__c[] lastTotals = [SELECT Id,As_of_Date__c FROM Engagement_Totals__c ORDER BY As_of_Date__c DESC LIMIT 1];
		if (lastTotals.size() == 0) {
			noRecentData = true;
		} else {
			date lastDate = lastTotals[0].As_of_Date__c;
			if (lastDate.daysBetween(System.today()) > 7) {
				noRecentData = true;
			}  else {
				// query for all the totals from that date
				Engagement_Totals__c[] results = [Select Engagement_Level__c, Number_of_Contacts__c  
					FROM Engagement_Totals__c WHERE As_of_Date__c = :lastDate
					ORDER BY Engagement_Level__c];
				
				for (Engagement_Totals__c result:results) {
					aggEngagementRow row = new aggEngagementRow();
					row.levelName = result.Engagement_Level__c;
					row.countCons = (integer) result.Number_of_Contacts__c;
					rows.add(row);
				}
			}
		}		
	}
	
	
	//wrapper class
	public class aggEngagementRow {
		
		public string levelName {get;set;}
		public integer countCons {get;set;} 
		
	}
	
    //--------------------TEST METHOD------------------------
    static testMethod void TestIt(){
    	
    	// insert some rows
    	list<Engagement_Totals__c> ets = new list<Engagement_Totals__c>(); 
    	for (integer i=0;i<7;i++) {
    		Engagement_Totals__c et = new Engagement_Totals__c (
    			Engagement_Level__c = (i+1) + ' - the level you love',
    			Number_of_Contacts__c = (i+1) * 100,
    			As_of_Date__c = system.today()
    		);
    		ets.add(et);
    	}
    	insert ets;
    	
        GW_CTRL_EngagementDashboard controller = new GW_CTRL_EngagementDashboard();
        controller.queryEngagementCounts();
        system.debug ('rows:' + controller.rows);
        system.debug ('noRecentData:' + controller.noRecentData);
    }

}